package org.domain.crud.entity;
// Generated 08/10/2015 20:06:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TaxOpcode generated by hbm2java
 */
@Entity
@Table(name = "request_state")
@XmlRootElement
public class RequestState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1864551567293374642L;
	@Id
	@SequenceGenerator(name="request_state_id_seq", sequenceName="request_state_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="request_state_id_seq")
	@Column(columnDefinition="serial")
	private Integer id;
	private Integer stockAction;
	private Integer type;
	private Integer prev;
	private Integer next;
	private String name;
	private String description;

	public RequestState() {
	}

	public RequestState(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "stock_action")
	public Integer getStockAction() {
		return stockAction;
	}

	public void setStockAction(Integer stockAction) {
		this.stockAction = stockAction;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getPrev() {
		return prev;
	}

	public void setPrev(Integer prev) {
		this.prev = prev;
	}

	public Integer getNext() {
		return next;
	}

	public void setNext(Integer next) {
		this.next = next;
	}

}
