package org.domain.crud.entity;
// Generated 08/10/2015 20:06:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TaxOpcode generated by hbm2java
 */
@Entity
@Table(name = "stock_action", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
@XmlRootElement
public class StockAction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1864551567293374642L;
	private Integer id;
	@NotNull
	private String name;

	public StockAction() {
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
