package org.domain.badmt.entity;
// Generated 08/10/2015 20:06:22 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductAssembleProduct generated by hbm2java
 */
@Entity
@Table(name = "product_assemble_product", uniqueConstraints = @UniqueConstraint(columnNames = {
		"product_in", "product_out"}))
@XmlRootElement
public class ProductAssembleProduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7472466135064917509L;
	private Integer id;
	private int productOut;
	private int productIn;
	private BigDecimal amountIn;
	private BigDecimal factorLoseInAssemble;
	private BigDecimal factorLoseInDisassemble;

	public ProductAssembleProduct() {
	}

	public ProductAssembleProduct(int id) {
		this.id = id;
	}

	public ProductAssembleProduct(int id, int productOut,
			int productIn, BigDecimal amountIn,
			BigDecimal factorLoseInAssemble, BigDecimal factorLoseInDisassemble) {
		this.id = id;
		this.productOut = productOut;
		this.productIn = productIn;
		this.amountIn = amountIn;
		this.factorLoseInAssemble = factorLoseInAssemble;
		this.factorLoseInDisassemble = factorLoseInDisassemble;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_out", nullable = false)
	public int getProductOut() {
		return this.productOut;
	}

	public void setProductOut(int productOut) {
		this.productOut = productOut;
	}

	@Column(name = "product_in", nullable = false)
	public int getProductIn() {
		return this.productIn;
	}

	public void setProductIn(int productIn) {
		this.productIn = productIn;
	}

	@Column(name = "amount_in", precision = 9, scale = 3)
	public BigDecimal getAmountIn() {
		return this.amountIn;
	}

	public void setAmountIn(BigDecimal amountIn) {
		this.amountIn = amountIn;
	}

	@Column(name = "factor_lose_in_assemble", precision = 9, scale = 3)
	public BigDecimal getFactorLoseInAssemble() {
		return this.factorLoseInAssemble;
	}

	public void setFactorLoseInAssemble(BigDecimal factorLoseInAssemble) {
		this.factorLoseInAssemble = factorLoseInAssemble;
	}

	@Column(name = "factor_lose_in_disassemble", precision = 9, scale = 3)
	public BigDecimal getFactorLoseInDisassemble() {
		return this.factorLoseInDisassemble;
	}

	public void setFactorLoseInDisassemble(BigDecimal factorLoseInDisassemble) {
		this.factorLoseInDisassemble = factorLoseInDisassemble;
	}

}
