package org.domain.badmt.entity;
// Generated 08/10/2015 20:06:22 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ProductAssembleService generated by hbm2java
 */
@Entity
@Table(name = "product_assemble_service", uniqueConstraints = @UniqueConstraint(columnNames = {
		"service_in", "product_out"}))
@XmlRootElement
public class ProductAssembleService implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5436108262699283046L;
	private Integer id;
	private int productOut;
	private int serviceIn;
	private BigDecimal amountIn;

	public ProductAssembleService() {
	}

	public ProductAssembleService(int id) {
		this.id = id;
	}

	public ProductAssembleService(int id, int product, int service,
			BigDecimal amountIn) {
		this.id = id;
		this.productOut = product;
		this.serviceIn = service;
		this.amountIn = amountIn;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_out", nullable = false)
	public int getProductOut() {
		return this.productOut;
	}

	public void setProductOut(int product) {
		this.productOut = product;
	}

	@Column(name = "service_in", nullable = false)
	public int getServiceIn() {
		return this.serviceIn;
	}

	public void setServiceIn(int service) {
		this.serviceIn = service;
	}

	@Column(name = "amount_in", precision = 9, scale = 3)
	public BigDecimal getAmountIn() {
		return this.amountIn;
	}

	public void setAmountIn(BigDecimal amountIn) {
		this.amountIn = amountIn;
	}

}
