package org.domain.financial2.entity;

// Generated 24/10/2014 09:14:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productwithoutcard generated by hbm2java
 */
@Entity
@Table(name = "iso8583_tef_product_without_card")
public class ISO8583TefProductWithoutCard implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3740647398193912516L;
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	private String flows;
	private Integer provider;

	public ISO8583TefProductWithoutCard() {
	}

	public ISO8583TefProductWithoutCard(int id) {
		this.id = id;
	}

	public ISO8583TefProductWithoutCard(int id, String flows, Integer provider) {
		this.id = id;
		this.flows = flows;
		this.provider = provider;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFlows() {
		return this.flows;
	}

	public void setFlows(String flows) {
		this.flows = flows;
	}

	public Integer getProvider() {
		return this.provider;
	}

	public void setProvider(Integer provider) {
		this.provider = provider;
	}

}
