package org.domain.financial2.entity;

// Generated 24/10/2014 09:14:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "iso8583_tef_question")
public class ISO8583TefQuestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8462809327693205269L;
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	private Integer flags;
	private Integer mask;
	@Column(name = "val_max")
	private Integer valMax;
	@Column(name = "val_min")
	private Integer valMin;
	private String text;

	public ISO8583TefQuestion() {
	}

	public ISO8583TefQuestion(int id) {
		this.id = id;
	}

	public ISO8583TefQuestion(int id, Integer flags, Integer mask, Integer max,
			Integer min, String text) {
		this.id = id;
		this.flags = flags;
		this.mask = mask;
		this.valMax = max;
		this.valMin = min;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getFlags() {
		return this.flags;
	}

	public void setFlags(Integer flags) {
		this.flags = flags;
	}

	public Integer getMask() {
		return this.mask;
	}

	public void setMask(Integer mask) {
		this.mask = mask;
	}

	public Integer getValMax() {
		return this.valMax;
	}

	public void setValMax(Integer max) {
		this.valMax = max;
	}

	public Integer getValMin() {
		return this.valMin;
	}

	public void setValMin(Integer min) {
		this.valMin = min;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
