package org.domain.financial2.entity;

// Generated 24/10/2014 09:14:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Flow generated by hbm2java
 */
@Entity
@Table(name = "iso8583_tef_flow")
public class ISO8583TefFlow implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6105240152718157661L;
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "flags")
	private Integer flags;
	@Column(name = "questions")
	private String questions;
	@Column(name = "text")
	private String text;

	public ISO8583TefFlow() {
	}

	public ISO8583TefFlow(int id) {
		this.id = id;
	}

	public ISO8583TefFlow(int id, Integer flags, String questions, String text) {
		this.id = id;
		this.flags = flags;
		this.questions = questions;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFlags() {
		return this.flags;
	}

	public void setFlags(Integer flags) {
		this.flags = flags;
	}

	public String getQuestions() {
		return this.questions;
	}

	public void setQuestions(String questions) {
		this.questions = questions;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
