package org.domain.financial2.entity;

// Generated 24/10/2014 09:14:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "iso8583_tef_product")
public class ISO8583TefProduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3418364636516157324L;
	@Id
	private Integer id;
	@Column(name = "code_process")
	private Integer codeProcess;
	private Integer flags;
	private String flows;
	@Column(name = "msg_type")
	private Integer msgType;
	private String text;

	public ISO8583TefProduct() {
	}

	public ISO8583TefProduct(Integer codeProcess, Integer flags, String flows,
			Integer msgType, String text) {
		this.codeProcess = codeProcess;
		this.flags = flags;
		this.flows = flows;
		this.msgType = msgType;
		this.text = text;
	}

	public Integer getCodeProcess() {
		return this.codeProcess;
	}

	public void setCodeProcess(Integer codeProcess) {
		this.codeProcess = codeProcess;
	}

	public Integer getFlags() {
		return this.flags;
	}

	public void setFlags(Integer flags) {
		this.flags = flags;
	}

	public String getFlows() {
		return this.flows;
	}

	public void setFlows(String flows) {
		this.flows = flows;
	}

	public Integer getMsgType() {
		return this.msgType;
	}

	public void setMsgType(Integer msgType) {
		this.msgType = msgType;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}
