package org.domain.financial2.entity;

// Generated 24/10/2014 09:14:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bin generated by hbm2java
 */
@Entity
@Table(name = "iso8583_pos_frete_money")
public class ISO8583PosFreteMoney implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -4319570188097885556L;
	@Id
	private Integer code;
	private String flags;
	private String symbol;
	@Column(name = "symbol_side")
	private Integer symbolSide;
	@Column(name = "symbol_separator")
	private Integer centsSeparator;
	@Column(name = "exponent_tag_5f36")
	private Integer exponentTag_5f36;

	public Integer getCode() {
		return code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public String getFlags() {
		return flags;
	}

	public void setFlags(String flags) {
		this.flags = flags;
	}

	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Integer getSymbolSide() {
		return symbolSide;
	}

	public void setSymbolSide(Integer symbolSide) {
		this.symbolSide = symbolSide;
	}

	public Integer getCentsSeparator() {
		return centsSeparator;
	}

	public void setCentsSeparator(Integer centsSeparator) {
		this.centsSeparator = centsSeparator;
	}

	public Integer getExponentTag_5f36() {
		return exponentTag_5f36;
	}

	public void setExponentTag_5f36(Integer exponentTag_5f36) {
		this.exponentTag_5f36 = exponentTag_5f36;
	}

	public ISO8583PosFreteMoney() {
	}

	public ISO8583PosFreteMoney(int code) {
		this.code = code;
	}

}
